// AUTO-GENERATED by scripts/generate_destinations.py — do not edit

export function getImage(slug: string | null): number | null {
  switch (slug) {
    case 'ahmedabad': return require('./images/ahmedabad.jpg');
    case 'baghdad': return require('./images/baghdad.jpg');
    case 'beijing': return require('./images/beijing.jpg');
    case 'cairo': return require('./images/cairo.jpg');
    case 'chengdu': return require('./images/chengdu.jpg');
    case 'chongqing': return require('./images/chongqing.jpg');
    case 'delhi': return require('./images/delhi.jpg');
    case 'dhaka': return require('./images/dhaka.jpg');
    case 'dongguan': return require('./images/dongguan.jpg');
    case 'guangzhou': return require('./images/guangzhou.jpg');
    case 'ho-chi-minh-city': return require('./images/ho-chi-minh-city.jpg');
    case 'hyderabad': return require('./images/hyderabad.jpg');
    case 'istanbul': return require('./images/istanbul.jpg');
    case 'johannesburg': return require('./images/johannesburg.jpg');
    case 'karachi': return require('./images/karachi.jpg');
    case 'kinshasa': return require('./images/kinshasa.jpg');
    case 'lahore': return require('./images/lahore.jpg');
    case 'mexico-city': return require('./images/mexico-city.jpg');
    case 'moscow': return require('./images/moscow.jpg');
    case 'mumbai': return require('./images/mumbai.jpg');
    case 'nanjing': return require('./images/nanjing.jpg');
    case 'qingdao': return require('./images/qingdao.jpg');
    case 'rio-de-janeiro': return require('./images/rio-de-janeiro.jpg');
    case 'sao-paulo': return require('./images/sao-paulo.jpg');
    case 'seoul': return require('./images/seoul.jpg');
    case 'shanghai': return require('./images/shanghai.jpg');
    case 'shenyang': return require('./images/shenyang.jpg');
    case 'shenzhen': return require('./images/shenzhen.jpg');
    case 'suzhou': return require('./images/suzhou.jpg');
    case 'tehran': return require('./images/tehran.jpg');
    case 'tianjin': return require('./images/tianjin.jpg');
    case 'tokyo': return require('./images/tokyo.jpg');
    case 'wuhan': return require('./images/wuhan.jpg');
    default: return null;
  }
}

export function getFallback(type: string): number | null {
  switch (type) {
    case 'city': return require('./fallbacks/city.jpg');
    case 'island': return require('./fallbacks/island.jpg');
    case 'nature': return require('./fallbacks/nature.jpg');
    default: return null;
  }
}
