// AUTO-GENERATED by scripts/generate_destinations.py — do not edit

export function getImage(slug: string | null): number | null {
  switch (slug) {
    case 'ahmedabad': return require('./images/ahmedabad.jpg');
    case 'alexandria': return require('./images/alexandria.jpg');
    case 'baghdad': return require('./images/baghdad.jpg');
    case 'bangkok': return require('./images/bangkok.jpg');
    case 'beijing': return require('./images/beijing.jpg');
    case 'bengaluru': return require('./images/bengaluru.jpg');
    case 'cairo': return require('./images/cairo.jpg');
    case 'cape-town': return require('./images/cape-town.jpg');
    case 'changchun': return require('./images/changchun.jpg');
    case 'chengdu': return require('./images/chengdu.jpg');
    case 'chennai': return require('./images/chennai.jpg');
    case 'chongqing': return require('./images/chongqing.jpg');
    case 'dalian': return require('./images/dalian.jpg');
    case 'dar-es-salaam': return require('./images/dar-es-salaam.jpg');
    case 'delhi': return require('./images/delhi.jpg');
    case 'dhaka': return require('./images/dhaka.jpg');
    case 'dongguan': return require('./images/dongguan.jpg');
    case 'foshan': return require('./images/foshan.jpg');
    case 'guangzhou': return require('./images/guangzhou.jpg');
    case 'hangzhou': return require('./images/hangzhou.jpg');
    case 'hanoi': return require('./images/hanoi.jpg');
    case 'harbin': return require('./images/harbin.jpg');
    case 'hefei': return require('./images/hefei.jpg');
    case 'ho-chi-minh-city': return require('./images/ho-chi-minh-city.jpg');
    case 'hyderabad': return require('./images/hyderabad.jpg');
    case 'istanbul': return require('./images/istanbul.jpg');
    case 'jakarta': return require('./images/jakarta.jpg');
    case 'jeddah': return require('./images/jeddah.jpg');
    case 'jinan': return require('./images/jinan.jpg');
    case 'johannesburg': return require('./images/johannesburg.jpg');
    case 'kabul': return require('./images/kabul.jpg');
    case 'karachi': return require('./images/karachi.jpg');
    case 'kinshasa': return require('./images/kinshasa.jpg');
    case 'kolkata': return require('./images/kolkata.jpg');
    case 'lagos': return require('./images/lagos.jpg');
    case 'lahore': return require('./images/lahore.jpg');
    case 'lima': return require('./images/lima.jpg');
    case 'london': return require('./images/london.jpg');
    case 'melbourne': return require('./images/melbourne.jpg');
    case 'mexico-city': return require('./images/mexico-city.jpg');
    case 'moscow': return require('./images/moscow.jpg');
    case 'mumbai': return require('./images/mumbai.jpg');
    case 'nairobi': return require('./images/nairobi.jpg');
    case 'nanjing': return require('./images/nanjing.jpg');
    case 'new-york-city': return require('./images/new-york-city.jpg');
    case 'peshawar': return require('./images/peshawar.jpg');
    case 'qingdao': return require('./images/qingdao.jpg');
    case 'rio-de-janeiro': return require('./images/rio-de-janeiro.jpg');
    case 'saint-petersburg': return require('./images/saint-petersburg.jpg');
    case 'santiago': return require('./images/santiago.jpg');
    case 'sao-paulo': return require('./images/sao-paulo.jpg');
    case 'seoul': return require('./images/seoul.jpg');
    case 'shanghai': return require('./images/shanghai.jpg');
    case 'shenyang': return require('./images/shenyang.jpg');
    case 'shenzhen': return require('./images/shenzhen.jpg');
    case 'suzhou': return require('./images/suzhou.jpg');
    case 'sydney': return require('./images/sydney.jpg');
    case 'taipei': return require('./images/taipei.jpg');
    case 'taiyuan': return require('./images/taiyuan.jpg');
    case 'tehran': return require('./images/tehran.jpg');
    case 'tianjin': return require('./images/tianjin.jpg');
    case 'tokyo': return require('./images/tokyo.jpg');
    case 'wuhan': return require('./images/wuhan.jpg');
    case 'wuxi': return require('./images/wuxi.jpg');
    case 'xiamen': return require('./images/xiamen.jpg');
    case 'yangon': return require('./images/yangon.jpg');
    case 'zhengzhou': return require('./images/zhengzhou.jpg');
    default: return null;
  }
}

export function getFallback(type: string): number | null {
  switch (type) {
    case 'city': return require('./fallbacks/city.jpg');
    case 'island': return require('./fallbacks/island.jpg');
    case 'nature': return require('./fallbacks/nature.jpg');
    default: return null;
  }
}
